theme: jekyll-theme-minimal
title: Oscar's winners vs user's ratings
description: Data story about Oscar's winners and users' ratings by team bADAboum for the EPFL ADA course
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
